### ISSUE TITLE
Using LowRankModels, DataFrames does not import fit!(g::GLRM) into the namespace

### ISSUE THREAD

**Issue by alejandroschuler** [madeleineudell/LowRankModels.jl#20]
```julia
julia> using DataFrames, LowRankModels

julia> methods(fit!)
# 1 method for generic function "fit!":
fit!(glrm::GLRM) at /Users/aschuler/.julia/v0.3/LowRankModels/src/glrm.jl:171
```
but (note the order of the `using` statement):

```julia
julia> using LowRankModels, DataFrames

julia> methods(fit!)
# 1 method for generic function "fit!":
fit!(obj::StatisticalModel,data...) at /Users/aschuler/.julia/v0.3/StatsBase/src/statmodels.jl:14
```

**Comment by madeleineudell** [comment]
Looks like the `fit!` methods of the two packages overwrite each other
instead of adding new methods to the methods table. You should raise this
issue on julialang/julia or ask a question about it on [julia-users](
https://groups.google.com/forum/#!forum/julia-users).

On Mon, Jul 6, 2015 at 11:25 AM, Alejandro Schuler <notifications@github.com
> wrote:

> julia> using DataFrames, LowRankModels
>
> julia> methods(fit!)# 1 method for generic function "fit!":fit!(glrm::GLRM) at /Users/aschuler/.julia/v0.3/LowRankModels/src/glrm.jl:171
>
> but (note the order of the using statement):
>
> julia> using LowRankModels, DataFrames
> Warning: using LowRankModels.scale in module Main conflicts with an existing identifier.
>
> julia> methods(fit!)# 1 method for generic function "fit!":fit!(obj::StatisticalModel,data...) at /Users/aschuler/.julia/v0.3/StatsBase/src/statmodels.jl:14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/20>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by madeleineudell** [comment]
This topic is discussed [on this thread](https://groups.google.com/forum/#!topic/julia-users/sk8Gxq7ws3w%5B1-25%5D) of julia-users.
