### ISSUE TITLE
svd warm start is not working

### ISSUE THREAD

**Issue by alejandroschuler** [madeleineudell/LowRankModels.jl#7]
I have a glrm model that runs fine by itself and also with kmeans++, but breaks when I try to initialize it with svd:

```
ERROR: BoundsError()
 in checkbounds at abstractarray.jl:65
 in setindex! at multidimensional.jl:61
 in setindex! at sharedarray.jl:216
 in init_svd! at /home/aschuler/.julia/v0.3/LowRankModels/src/initialize.jl:70
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/aschuler/LatentSyndromes/src/run.jl, in expression starting on line 56
```

Problem persists even when I use a simple glrm:
```
using LowRankModels
import StatsBase: sample

srand(1)
	m,n,k,s = 1000, 1000, 5, 50000
	A = randn(m,k)*randn(k,n)
	losses = fill(quadratic(),n)
	r = quadreg(.1)
	obsx = [sample(1:int(m/4),int(s/2)), sample(int(m/4)+1:m,s-int(s/2))] 
	obsy = sample(1:n,s)
	obs = [(obsx[i],obsy[i]) for i=1:s]
	glrm = GLRM(A,obs,losses,r,r,k)
        @time init_svd!(glrm)
ERROR: BoundsError()
 in checkbounds at abstractarray.jl:65
 in setindex! at multidimensional.jl:61
 in setindex! at sharedarray.jl:216
 in init_svd! at /home/aschuler/.julia/v0.3/LowRankModels/src/initialize.jl:70
```
**However, it works fine using the serial implementation.**

**Comment by alejandroschuler** [comment]
I think this is the offending line:
```
glrm.X[1:m,1:k] = u[:,1:k]*diagm(sqrt(s[1:k]))
```
Which I suspect doesn't like:
```
    # make sure that we've oriented the factors as shareglrm expects
    if size(glrm.Y,1)!==size(glrm.X,1)
        glrm.X = glrm.X'
    end
```
which is in the shareglrm code. 

So the three options are:
1. Change all the code to accept the transposed X format that `shareglrm` uses.
2. Change `shareglrm` to use a non-transposed version of X
3. Change all the code to check whether or not shareglrm is being used and act accordingly.

I think option #2 seems the most reasonable, but then again I'm not sure why shareglrm is implemented with that transposition in the first place, so presumably there's a good reason. Barring that, option #3 is a bit silly and would be harder to maintain, so option #1 is the best bet?

**Comment by madeleineudell** [comment]
The reason `shareglrm` uses the transposed X format is because Julia stores
matrices in column-major order, so iterating over entries in the same
column is faster than entries in the same row. Since the fitting procedure
deals with columns of Y and rows of X, here we store the rows of X as
columns for increased efficiency, which becomes increasingly important in
the kinds of large models we expect to be input to `shareglrm`.

Or at least, that's the theory behind the madness. I haven't tested
extensively to find out if it makes a big difference. (And as long as we
don't know why we're seeing such high GC levels, I remain open to all
hypotheses.)

So I'd propose option 2, perhaps, unless it turns out upon testing that
it's substantially slower to fit, in which case I'd propose option 1. I
agree option 3 is silly, although it is in some sense the status quo.

On Thu, May 28, 2015 at 7:22 PM, Alejandro Schuler <notifications@github.com
> wrote:

> I think this is the offending line:
>
> glrm.X[1:m,1:k] = u[:,1:k]*diagm(sqrt(s[1:k]))
>
> Which I suspect doesn't like:
>
>     # make sure that we've oriented the factors as shareglrm expects
>     if size(glrm.Y,1)!==size(glrm.X,1)
>         glrm.X = glrm.X'
>     end
>
> which is in the shareglrm code.
>
> So the three options are:
> 1. Change all the code to accept the transposed X format that shareglrm
> uses.
> 2. Change shareglrm to use a non-transposed version of X
> 3. Change all the code to check whether or not shareglrm is being used and
> act accordingly.
>
> I think option #2
> <https://github.com/madeleineudell/LowRankModels.jl/issues/2> seems the
> most reasonable, but then again I'm not sure why shareglrm is implemented
> with that transposition in the first place, so presumably there's a good
> reason. Barring that, option #3
> <https://github.com/madeleineudell/LowRankModels.jl/pull/3> is a bit
> silly and would be harder to maintain, so option #1
> <https://github.com/madeleineudell/LowRankModels.jl/pull/1> is the best
> bet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/7#issuecomment-106659265>
> .
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by alejandroschuler** [comment]
Ahhh, yes, that does make sense. In that case, the same logic should apply to the serial version and even if it doesn't make a big difference, it'd be a good long-term idea to implement them both with that transposition. I'll see if I can take care of it tomorrow.

**Comment by alejandroschuler** [comment]
Fixed in my latest commit- changed all code to expect glrm.X to be k-by-n instead of n-by-k. Also changed the returns of `fit!` to return X' as a user would expect.
